export const BUSINESS_BY_NAME_LOADING ="BUSINESS_BY_NAME_LOADING"
export const BUSINESS_BY_NAME_SUCCESS = "BUSINESS_BY_NAME_SUCCESS"
export const BUSINESS_BY_NAME_FAIL = "BUSINESS_BY_NAME_FAIL"

export const SET_BUSINESS_NAME = "SET_BUSINESS_NAME"
export const SET_LOCATION_STATE = "SET_LOCATION_STATE"
export const SET_LOCATION_CITY = "SET_LOCATION_CITY"
export const SET_LOCATION_ZIPCODE = "SET_LOCATION_ZIPCODE"

export const INCLUDED_LOCATIONS_LOADING = "INCLUDED_LOCATIONS_LOADING"
export const INCLUDED_LOCATIONS_SUCCESS = "INCLUDED_LOCATIONS_SUCCESS"
export const INCLUDED_LOCATIONS_FAIL = "INCLUDED_LOCATIONS_FAIL"

export const GET_STATE_LIST = "GET_STATE_LIST"